server:
  port: 8888

spring:
  application:
    name: config-server-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shashi4862/pizzeria-config
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
