server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/menu/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
