server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/payments/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/deliveries/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
